
#####
# ASSIGN VECTOR OF COUNTY NAMES
#####
counties <- c("alachua",
              "baker",
              "bay",
              "bradford",
              "brevard",
              "broward",
              "calhoun",
              "charlotte",
              "citrus",
              "clay",
              "collier",
              "columbia",
              "desoto",
              "dixie",
              "duval",
              "escambia",
              "flagler",
              "franklin",
              "gadsden",
              "gilchrist",
              "glades",
              "gulf",
              "hamilton",
              "hardee",
              "hendry",
              "hernando",
              "highlands",
              "hillsborough",
              "holmes",
              "indian river",
              "jackson",
              "jefferson",
              "lafayette",
              "lake",
              "lee",
              "leon",
              "levy",
              "liberty",
              "madison",
              "manatee",
              "marion",
              "martin",
              "miami-dade",
              "monroe",
              "nassau",
              "okaloosa",
              "okeechobee",
              "orange",
              "osceola",
              "palm beach",
              "pasco",
              "pinellas",
              "polk",
              "putnam",
              "st. johns",
              "st. lucie",
              "santa rosa",
              "sarasota",
              "seminole",
              "sumter",
              "suwannee",
              "taylor",
              "union",
              "volusia",
              "wakulla",
              "walton",
              "washington")